import 'package:flutter/material.dart';
import 'challenge.dart';

// Tous les défis basés sur les fonctionnalités
final List<Challenge> allChallenges = [
  // Catégorie 2 : Habitudes de consommation (12 fonctionnalités)
  Challenge(
    id: '1',
    title: 'Consommation quotidienne d\'eau potable',
    description: 'Litres d\'eau potable consommés quotidiennement',
    icon: Icons.local_drink,
    points: 30,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 10,
  ),
  Challenge(
    id: '2',
    title: 'Durée moyenne des douches',
    description: 'Quelle est la durée moyenne de vos douches (en minutes) ?',
    icon: Icons.shower,
    points: 70,
    category: 'habits',
    inputType: 'slider',
    min: 1,
    max: 30,
  ),
  Challenge(
    id: '3',
    title: 'Bains par mois',
    description: 'Combien de bains prenez-vous par mois ?',
    icon: Icons.bathtub,
    points: 40,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 30,
  ),
  Challenge(
    id: '4',
    title: 'Eau pour les pratiques religieuses',
    description: 'Utilisez-vous de l\'eau pour des pratiques religieuses ?',
    icon: Icons.water,
    points: 25,
    category: 'habits',
    inputType: 'radio',
    options: ['Oui', 'Non'],
  ),
  Challenge(
    id: '5',
    title: 'Douches hebdomadaires',
    description: 'Combien de douches prenez-vous par semaine ?',
    icon: Icons.shower,
    points: 45,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 21,
  ),
  Challenge(
    id: '6',
    title: 'Durée moyenne des bains',
    description: 'Durée moyenne des bains (en minutes)',
    icon: Icons.bathtub,
    points: 35,
    category: 'habits',
    inputType: 'slider',
    min: 1,
    max: 60,
  ),
  Challenge(
    id: '7',
    title: 'Utilisation d\'eau pour la cuisine',
    description: 'Combien d\'eau utilisez-vous pour cuisiner quotidiennement (en litres) ?',
    icon: Icons.restaurant,
    points: 30,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 50,
  ),
  Challenge(
    id: '8',
    title: 'Fréquence de chasse d\'eau',
    description: 'Combien de fois tirez-vous la chasse d\'eau par jour ?',
    icon: Icons.water_damage,
    points: 50,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 30,
  ),
  Challenge(
    id: '9',
    title: 'Utilisation de la machine à laver',
    description: 'Combien de cycles de machine à laver effectuez-vous par semaine ?',
    icon: Icons.local_laundry_service,
    points: 50,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 20,
  ),
  Challenge(
    id: '10',
    title: 'Utilisation du lave-vaisselle',
    description: 'Combien de cycles de lave-vaisselle effectuez-vous par semaine ?',
    icon: Icons.countertops,
    points: 40,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 14,
  ),
  Challenge(
    id: '11',
    title: 'Fréquence de lavage de voiture',
    description: 'Combien de fois lavez-vous votre voiture par mois ?',
    icon: Icons.directions_car,
    points: 30,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 30,
  ),
  Challenge(
    id: '12',
    title: 'Nombre de véhicules',
    description: 'Combien de véhicules possède votre ménage ?',
    icon: Icons.directions_car,
    points: 20,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 5,
  ),

  // Catégorie 3 : Données Sociodémographiques (8 fonctionnalités)
  Challenge(
    id: '13',
    title: 'Revenu Mensuel du Ménage',
    description: 'Quel est le revenu mensuel moyen de votre ménage ?',
    icon: Icons.attach_money,
    points: 40,
    category: 'sociodemographic',
    inputType: 'dropdown',
    options: [
      'Moins de 5 000 Dhs',
      '5 000 - 10 000 Dhs',
      '10 000 - 20 000 Dhs',
      '20 000 - 30 000 Dhs',
      'Plus de 30 000 Dhs',
      'Je préfère ne pas répondre'
    ],
  ),
 
  Challenge(
    id: '15',
    title: 'Niveau d\'Éducation',
    description: 'Quel est votre niveau d\'éducation le plus élevé ?',
    icon: Icons.school,
    points: 30,
    category: 'sociodemographic',
    inputType: 'dropdown',
    options: [
      'École primaire',
      'École secondaire',
      'Lycée',
      'Licence',
      'Master',
      'Doctorat',
      'Autre'
    ],
  ),
 
  Challenge(
    id: '17',
    title: 'Sensibilisation à l\'Environnement',
    description: 'Comment évaluez-vous votre sensibilisation à l\'environnement ? (1-5)',
    icon: Icons.nature_people,
    points: 50,
    category: 'sociodemographic',
    inputType: 'slider',
    min: 1,
    max: 5,
  ),
  Challenge(
    id: '32',
    title: 'Accès à un Plombier',
    description: 'Avez-vous accès à un plombier de confiance ?',
    icon: Icons.handyman,
    points: 40,
    category: 'sociodemographic',
    inputType: 'radio',
    options: ['Oui', 'Non'],
  ),

];