import 'package:flutter/material.dart';
import 'challenge.dart';

// All 41 challenges based on the features
final List<Challenge> allChallenges = [
  // Category 1: Structural Housing Characteristics (12 features)
  Challenge(
    id: '1',
    title: 'Plumbing Age',
    description: 'How old is your home\'s plumbing system (in years)?',
    icon: Icons.plumbing,
    points: 50,
    category: 'structural',
    inputType: 'number',
    min: 0,
    max: 100,
  ),
  Challenge(
    id: '2',
    title: 'Toilet Count',
    description: 'How many toilets/flush systems do you have in your home?',
    icon: Icons.wc,
    points: 30,
    category: 'structural',
    inputType: 'number',
    min: 0,
    max: 10,
  ),
  Challenge(
    id: '3',
    title: 'Faucet Count',
    description: 'Count the total number of faucets (indoor + outdoor) in your home',
    icon: Icons.water_drop,
    points: 40,
    category: 'structural',
    inputType: 'number',
    min: 0,
    max: 20,
  ),
  Challenge(
    id: '4',
    title: 'Pipe Material',
    description: 'What type of pipes are used in your home\'s plumbing?',
    icon: Icons.line_style,
    points: 60,
    category: 'structural',
    inputType: 'dropdown',
    options: ['Copper', 'PVC', 'Lead', 'Galvanized Steel', 'PEX', 'Other', 'I don\'t know'],
  ),
  Challenge(
    id: '5',
    title: 'Irrigation System',
    description: 'Do you have an automatic irrigation system?',
    icon: Icons.grass,
    points: 30,
    category: 'structural',
    inputType: 'radio',
    options: ['Yes', 'No'],
  ),
  Challenge(
    id: '6',
    title: 'Garden Size',
    description: 'What is the approximate size of your garden/terrace (in square meters)?',
    icon: Icons.yard,
    points: 40,
    category: 'structural',
    inputType: 'number',
    min: 0,
    max: 1000,
  ),
  Challenge(
    id: '7',
    title: 'Home Floors',
    description: 'How many floors does your home have?',
    icon: Icons.home,
    points: 20,
    category: 'structural',
    inputType: 'number',
    min: 1,
    max: 10,
  ),
  Challenge(
    id: '8',
    title: 'Last Plumbing Renovation',
    description: 'When was the last time your plumbing was renovated (year)?',
    icon: Icons.build,
    points: 50,
    category: 'structural',
    inputType: 'number',
    min: 1950,
    max: 2025,
  ),
  Challenge(
    id: '9',
    title: 'Water Heater Type',
    description: 'What type of water heater do you use?',
    icon: Icons.hot_tub,
    points: 40,
    category: 'structural',
    inputType: 'dropdown',
    options: ['Electric', 'Gas', 'Solar', 'Heat Pump', 'Tankless', 'Other'],
  ),
  Challenge(
    id: '10',
    title: 'Swimming Pool',
    description: 'Do you have a swimming pool?',
    icon: Icons.pool,
    points: 30,
    category: 'structural',
    inputType: 'radio',
    options: ['Yes', 'No'],
  ),
  Challenge(
    id: '11',
    title: 'Bathroom Count',
    description: 'How many bathrooms do you have?',
    icon: Icons.bathroom,
    points: 30,
    category: 'structural',
    inputType: 'number',
    min: 0,
    max: 10,
  ),
  Challenge(
    id: '12',
    title: 'Main Pipe Material',
    description: 'What material are your main water pipes made of?',
    icon: Icons.settings_input_component,
    points: 60,
    category: 'structural',
    inputType: 'dropdown',
    options: ['Steel', 'HDPE', 'PVC', 'Cast Iron', 'Other', 'I don\'t know'],
  ),

  // Category 2: Consumption Habits and Behaviors (14 features)
  Challenge(
    id: '13',
    title: 'Shower Duration',
    description: 'What is the average duration of your showers (minutes per day per person)?',
    icon: Icons.shower,
    points: 70,
    category: 'habits',
    inputType: 'slider',
    min: 1,
    max: 30,
  ),
  Challenge(
    id: '14',
    title: 'Washing Machine Usage',
    description: 'How many washing machine cycles do you run per week?',
    icon: Icons.local_laundry_service,
    points: 50,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 20,
  ),
  Challenge(
    id: '15',
    title: 'Dishwasher Usage',
    description: 'How often do you use your dishwasher per week?',
    icon: Icons.countertops,
    points: 40,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 14,
  ),
  Challenge(
    id: '16',
    title: 'Bath Frequency',
    description: 'How many baths do you take per month?',
    icon: Icons.bathtub,
    points: 40,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 30,
  ),
  Challenge(
    id: '17',
    title: 'Garden Watering Method',
    description: 'How do you water your garden?',
    icon: Icons.water,
    points: 50,
    category: 'habits',
    inputType: 'dropdown',
    options: ['Manual watering can', 'Hose', 'Drip irrigation', 'Sprinkler system', 'No garden'],
  ),
  Challenge(
    id: '18',
    title: 'Car Washing',
    description: 'How often do you wash your car at home?',
    icon: Icons.directions_car,
    points: 30,
    category: 'habits',
    inputType: 'dropdown',
    options: ['Never', 'Monthly', 'Bi-weekly', 'Weekly', 'More than once a week'],
  ),
  Challenge(
    id: '19',
    title: 'Self-Reported Leaks',
    description: 'Have you noticed any leaks in the past 6 months?',
    icon: Icons.opacity,
    points: 60,
    category: 'habits',
    inputType: 'radio',
    options: ['Yes', 'No'],
  ),
  Challenge(
    id: '20',
    title: 'Repair Response Time',
    description: 'How quickly do you typically respond to plumbing issues?',
    icon: Icons.timer,
    points: 70,
    category: 'habits',
    inputType: 'dropdown',
    options: ['Within 24 hours', '1-3 days', '4-7 days', 'More than a week', 'I ignore them'],
  ),
  Challenge(
    id: '21',
    title: 'Night Water Usage',
    description: 'Do you regularly use water after 10 PM?',
    icon: Icons.nightlight_round,
    points: 40,
    category: 'habits',
    inputType: 'radio',
    options: ['Yes', 'No', 'Sometimes'],
  ),
  Challenge(
    id: '22',
    title: 'Floor Cleaning Water',
    description: 'How much water do you use for floor cleaning weekly (liters)?',
    icon: Icons.cleaning_services,
    points: 40,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 100,
  ),
  Challenge(
    id: '23',
    title: 'Toilet Flushing',
    description: 'How many times is your toilet flushed per day on average?',
    icon: Icons.water_damage,
    points: 50,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 30,
  ),
  Challenge(
    id: '24',
    title: 'Water-Saving Equipment',
    description: 'Do you have water-saving equipment installed?',
    icon: Icons.eco,
    points: 60,
    category: 'habits',
    inputType: 'checkbox',
    options: ['Low-flow showerhead', 'Dual-flush toilet', 'Faucet aerators', 'Water-efficient appliances', 'None'],
  ),
  Challenge(
    id: '25',
    title: 'Cooking Water Usage',
    description: 'How much water do you use for cooking daily (liters)?',
    icon: Icons.restaurant,
    points: 30,
    category: 'habits',
    inputType: 'number',
    min: 0,
    max: 50,
  ),
  Challenge(
    id: '26',
    title: 'Household Size',
    description: 'How many people live in your home permanently?',
    icon: Icons.people,
    points: 20,
    category: 'habits',
    inputType: 'number',
    min: 1,
    max: 15,
  ),

  // Category 3: Sociodemographic Data (8 features)
  Challenge(
    id: '27',
    title: 'Household Income',
    description: 'What is your monthly household income range?',
    icon: Icons.attach_money,
    points: 40,
    category: 'sociodemographic',
    inputType: 'dropdown',
    options: ['Less than 5,000 Dhs', '5,000-10,000 Dhs', '10,000-20,000 Dhs', '20,000-30,000 Dhs', 'More than 30,000 Dhs', 'Prefer not to say'],
  ),
  Challenge(
    id: '28',
    title: 'Occupancy Status',
    description: 'Are you a homeowner or a tenant?',
    icon: Icons.home_work,
    points: 30,
    category: 'sociodemographic',
    inputType: 'radio',
    options: ['Homeowner', 'Tenant'],
  ),
  Challenge(
    id: '29',
    title: 'Education Level',
    description: 'What is your highest level of education?',
    icon: Icons.school,
    points: 30,
    category: 'sociodemographic',
    inputType: 'dropdown',
    options: ['Primary school', 'Secondary school', 'High school', 'Bachelor\'s degree', 'Master\'s degree', 'Doctorate', 'Other'],
  ),
  Challenge(
    id: '30',
    title: 'Household Head Age',
    description: 'What is the age of the head of household?',
    icon: Icons.person,
    points: 20,
    category: 'sociodemographic',
    inputType: 'number',
    min: 18,
    max: 100,
  ),
  Challenge(
    id: '31',
    title: 'Environmental Awareness',
    description: 'How would you rate your environmental awareness? (1-5)',
    icon: Icons.nature_people,
    points: 50,
    category: 'sociodemographic',
    inputType: 'slider',
    min: 1,
    max: 5,
  ),
  Challenge(
    id: '32',
    title: 'Plumber Access',
    description: 'Do you have access to a trusted plumber?',
    icon: Icons.handyman,
    points: 40,
    category: 'sociodemographic',
    inputType: 'radio',
    options: ['Yes', 'No'],
  ),
  Challenge(
    id: '33',
    title: 'Bill Payment History',
    description: 'Have you ever delayed paying your water bill?',
    icon: Icons.receipt_long,
    points: 30,
    category: 'sociodemographic',
    inputType: 'radio',
    options: ['Yes', 'No'],
  ),
  Challenge(
    id: '34',
    title: 'Household Size',
    description: 'How many people live in your household?',
    icon: Icons.family_restroom,
    points: 20,
    category: 'sociodemographic',
    inputType: 'number',
    min: 1,
    max: 15,
  ),

  // Category 4: Bill and Consumption Analysis (7 features)
  Challenge(
    id: '35',
    title: 'Monthly Consumption',
    description: 'What is your average monthly water consumption (m³)?',
    icon: Icons.water,
    points: 80,
    category: 'consumption',
    inputType: 'number',
    min: 0,
    max: 100,
  ),
  Challenge(
    id: '36',
    title: 'Yearly Consumption Trend',
    description: 'What is the percentage increase in your water consumption over the last 12 months?',
    icon: Icons.trending_up,
    points: 70,
    category: 'consumption',
    inputType: 'number',
    min: -100,
    max: 100,
  ),
  Challenge(
    id: '37',
    title: 'Regional Comparison',
    description: 'How does your consumption compare to the regional average (e.g., 8m³ in Casablanca)?',
    icon: Icons.compare_arrows,
    points: 60,
    category: 'consumption',
    inputType: 'dropdown',
    options: ['Much lower', 'Slightly lower', 'About the same', 'Slightly higher', 'Much higher'],
  ),
  Challenge(
    id: '38',
    title: 'Consumption Peaks',
    description: 'When do you notice peaks in your water consumption?',
    icon: Icons.show_chart,
    points: 50,
    category: 'consumption',
    inputType: 'dropdown',
    options: ['Summer', 'Winter', 'Spring', 'Fall', 'No noticeable pattern'],
  ),
  Challenge(
    id: '39',
    title: 'Night Consumption',
    description: 'Do you have unexplained water consumption at night (>0.5 m³)?',
    icon: Icons.nightlight,
    points: 80,
    category: 'consumption',
    inputType: 'radio',
    options: ['Yes', 'No', 'I don\'t know'],
  ),
  Challenge(
    id: '40',
    title: 'Monthly Cost',
    description: 'What is your average monthly water bill (Dhs)?',
    icon: Icons.payments,
    points: 40,
    category: 'consumption',
    inputType: 'number',
    min: 0,
    max: 1000,
  ),
  Challenge(
    id: '41',
    title: 'Previous Leak Claims',
    description: 'How many times have you filed a leak claim in the past?',
    icon: Icons.report_problem,
    points: 60,
    category: 'consumption',
    inputType: 'number',
    min: 0,
    max: 20,
  ),
];

